# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 01:09
from __future__ import unicode_literals

from django.db import migrations, models

def update_slugs(apps, schema_editor):
    Post = apps.get_model("blog", "Post")

    for instance in Post.objects.all():
        instance.slug = '%s-%s' % (instance.slug, instance.object_id)
        instance.save()

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', max_length=140, unique=True),
            preserve_default=False,
        ),
    ]
