# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 01:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_slug'),
    ]

    operations = [
    ]
