# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171111_0218'),
        ('blog', '0004_auto_20171111_1012'),
    ]

    operations = [
    ]
